### PR TITLE
update extra dependencies to match 3.2 package

### PR DESCRIPTION
**Pull request by timkpaine**
```
Requires-Dist: python-dateutil (<3,>=2.7.5)
Requires-Dist: tenacity (<9,>=8)
Requires-Dist: python-daemon
Requires-Dist: tornado (<7,>=5.0)
Provides-Extra: jsonschema
Requires-Dist: jsonschema ; extra == 'jsonschema'
Provides-Extra: prometheus
Requires-Dist: prometheus-client (<0.15,>=0.5) ; extra == 'prometheus'
Provides-Extra: toml
Requires-Dist: toml (<2.0.0) ; extra == 'toml'
```

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by timkpaine** [comment]
@conda-forge/luigi  / @conda-forge/core good to go

**Comment by kwilcox** [comment]
LGTM. @ocefpaf assuming re-render to fix CircleCI issue?

**Comment by ocefpaf** [comment]
> LGTM. @ocefpaf assuming re-render to fix CircleCI issue?

Let's see. If not we'll have to delete the hook. We are moving away from CircleCI.

@conda-forge-admin, please rerender

**Comment by timkpaine** [comment]
thanks!

**Pull request merged**
